# Generated by Django 3.1.2 on 2020-11-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtId', models.IntegerField(unique=True)),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productSellerName', models.CharField(max_length=50)),
                ('productColor', models.CharField(max_length=50)),
                ('productImg', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
