# Generated by Django 3.1.2 on 2020-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0002_remove_product_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductCategory',
            field=models.CharField(choices=[('E', 'Electronics'), ('HS', 'HomeSupplies'), ('B', 'Books')], default='E', max_length=2),
            preserve_default=False,
        ),
    ]
