# Generated by Django 3.1.2 on 2020-11-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0003_product_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='l', upload_to='images/'),
            preserve_default=False,
        ),
    ]
